# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsImgModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='product_aboutusimgmodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=100)),
                ('text_bold', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('text_button', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='BreadcrumbsProductModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='product_breadcrumbsproductmodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('text_bold', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жирный текст')),
                ('img', models.ImageField(blank=True, default='images/def/def.jpg', null=True, upload_to='images/product', verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DescProductModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='product_descproductmodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('img', models.ImageField(blank=True, default='images/def/def.jpg', null=True, upload_to='images/product', verbose_name='Изображение')),
                ('title_full', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное наименование')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('title_product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('description_product', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Текст описания')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('series', models.CharField(max_length=100, verbose_name='Серия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('description_specification', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Полное описание')),
                ('spec_specification', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Технические характеристики')),
                ('legend_specification', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Условные обозначения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.GroupProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/def/def.jpg', upload_to='images/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(default='images/def/def.jpg', upload_to='images/product/icon')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('products', models.ManyToManyField(to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ThProductModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='product_thproductmodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
