# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bg_color',
            field=models.CharField(choices=[('Gray', 'bg_gray'), ('Darker', 'bg-primary_darker'), ('White', 'bg-white')], default=('Gray', 'bg_gray'), max_length=1),
        ),
    ]
