# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('product', '0003_remove_product_bg_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsImgModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='product_aboutusimgmodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=100)),
                ('text_bold', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('text_button', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
