# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 13:20
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('product', '0004_aboutusimgmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusimgmodel',
            name='test',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='test', to='cms.Placeholder'),
        ),
    ]
