# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_descproductmodel_thproductmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='images/def/def.jpg', upload_to='images/product/icon')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('products', models.ManyToManyField(to='product.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutusimgmodel',
            name='test',
        ),
    ]
