# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 06:23
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190418_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_specification',
            field=djangocms_text_ckeditor.fields.HTMLField(default='default'),
        ),
    ]
