# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 06:48
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_description_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='legend_specification',
            field=djangocms_text_ckeditor.fields.HTMLField(default='default'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_specification',
            field=djangocms_text_ckeditor.fields.HTMLField(default='default'),
        ),
    ]
