# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 07:05
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190418_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_specification',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='legend_specification',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_specification',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
    ]
