# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20190418_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproduct',
            name='button_text_us',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='description_product',
            field=djangocms_text_ckeditor.fields.HTMLField(default='text'),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='description_us',
            field=djangocms_text_ckeditor.fields.HTMLField(default='text'),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='img_us',
            field=models.ImageField(default='images/def/def.jpg', upload_to='images/product'),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='title_product',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='title_us',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
    ]
