# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('product', '0018_auto_20190422_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadcrumbsProductModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='product_breadcrumbsproductmodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('text_bold', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жирный текст')),
                ('img', models.ImageField(blank=True, default='images/def/def.jpg', null=True, upload_to='images/product', verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
