# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_breadcrumbsproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproduct',
            name='description_product',
            field=djangocms_text_ckeditor.fields.HTMLField(default='text'),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='title_product',
            field=models.CharField(default='text', max_length=100),
        ),
    ]
