# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20190422_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='description_product',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Текст описания'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='title_product',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
