# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_aboutusmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='default', max_length=30)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(default='default')),
                ('text_button', models.CharField(default='default', max_length=30)),
                ('img', models.ImageField(default='images/def/def.jpg', upload_to='images/about-us')),
                ('bg_color', models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AlertCtaModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_alertctamodel', serialize=False, to='cms.CMSPlugin')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(default='default')),
                ('text_button', models.CharField(default='default.', max_length=30)),
                ('bg_color', models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AlertMdlModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_alertmdlmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='default', max_length=100)),
                ('title_bold', models.CharField(default='default', max_length=30)),
                ('descriptoin', models.TextField(default='default')),
                ('button_title', models.CharField(default='default', max_length=30)),
                ('bg_color', models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_contactusmodel', serialize=False, to='cms.CMSPlugin')),
                ('bg_color', models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_footermodel', serialize=False, to='cms.CMSPlugin')),
                ('header_1', models.CharField(default='Testimonials', max_length=30)),
                ('header_2', models.CharField(default='Testimonials', max_length=30)),
                ('header_3', models.CharField(default='Testimonials', max_length=30)),
                ('description_1', models.TextField(default='default')),
                ('description_2', models.TextField(default='default')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LastBlogModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_lastblogmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='Latest Blog Posts', max_length=30)),
                ('bg_color', models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MenuBarModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_menubarmodel', serialize=False, to='cms.CMSPlugin')),
                ('phone_number', models.CharField(default='0-000-000-000', max_length=30)),
                ('phone_number_2', models.CharField(default='0-000-000-000', max_length=30)),
                ('email', models.CharField(default='info@admin.org', max_length=30)),
                ('locations', models.CharField(default='default', max_length=100)),
                ('button_text', models.CharField(default='default', max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PriceBoxModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_priceboxmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='default', max_length=30)),
                ('price', models.CharField(default='default', max_length=30)),
                ('descriptoin', models.TextField(default='default')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_pricemodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='default', max_length=30)),
                ('bg_color', models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ProductSectionModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_productsectionmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='default', max_length=30)),
                ('text', models.TextField(default='default')),
                ('bg_color', models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RecallBoxModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_recallboxmodel', serialize=False, to='cms.CMSPlugin')),
                ('avatar', models.ImageField(default='images/def/def.jpg', upload_to='images/recall')),
                ('name', models.CharField(default='default', max_length=30)),
                ('post', models.CharField(default='default', max_length=30)),
                ('text', models.TextField(default='default')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RecallModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_recallmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='Testimonials', max_length=30)),
                ('bg_color', models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_slideritem', serialize=False, to='cms.CMSPlugin')),
                ('text_bold', models.CharField(default='default', max_length=120)),
                ('text', models.CharField(default='default.', max_length=120)),
                ('text_button', models.CharField(default='default.', max_length=30)),
                ('img', models.ImageField(default='images/def/def.jpg', upload_to='images/slider')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_slidermodel', serialize=False, to='cms.CMSPlugin')),
                ('name_slider', models.CharField(default='default.', max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SmallFeaturesModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_smallfeaturesmodel', serialize=False, to='cms.CMSPlugin')),
                ('icon_code', models.CharField(default='far fa-user', max_length=30)),
                ('title', models.CharField(default='default.', max_length=30)),
                ('description', models.TextField(default='default.')),
                ('bg_color', models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SolutionSectionModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_solutionsectionmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='default', max_length=30)),
                ('text', models.TextField(default='default')),
                ('bg_color', models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
