# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='img',
            field=models.ImageField(default='static/images/work.jpg', upload_to='media/static/images/'),
        ),
    ]
