# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0002_remove_solutionsectionmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionsectionmodel',
            name='descriptions',
            field=models.TextField(default='default text'),
        ),
    ]
