# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('inex_page_home', '0003_auto_20190412_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCtaModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_alertctamodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(default='text', max_length=30)),
                ('text_button', models.CharField(default='Text.', max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
