# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0003_solutionsectionmodel_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallfeaturesmodel',
            name='icon_image',
            field=models.ImageField(blank=True, default='images/def/def.jpg', null=True, upload_to='images/smallFeatures', verbose_name='Изображение'),
        ),
    ]
