# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('inex_page_home', '0004_alertctamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleSectionModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_titlesectionmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='text', max_length=30)),
                ('text', models.TextField(default='text')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
