# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0004_smallfeaturesmodel_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='title',
            field=models.CharField(blank=True, default='default', max_length=30, null=True),
        ),
    ]
