# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0009_lastblogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='menubarmodel',
            name='email',
            field=models.CharField(default='info@admin.org', max_length=30),
        ),
    ]
