# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0010_menubarmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menubarmodel',
            name='locations',
            field=models.CharField(default='Улица Правды 30, Витебск 210029', max_length=100),
        ),
    ]
