# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0011_auto_20190415_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='text_button',
            field=models.CharField(default='Text.', max_length=30),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='text',
            field=models.CharField(default='Text.', max_length=120),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='text_bold',
            field=models.CharField(default='Text. Text.', max_length=120),
        ),
    ]
