# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0012_auto_20190415_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='text_button',
            field=models.CharField(default='Text', max_length=30),
        ),
    ]
