# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('inex_page_home', '0013_aboutusmodel_text_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallBoxModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_recallboxmodel', serialize=False, to='cms.CMSPlugin')),
                ('avatar', models.ImageField(default='images/def/def.jpg', upload_to='images/recall')),
                ('name', models.CharField(default='default', max_length=30)),
                ('post', models.CharField(default='default', max_length=30)),
                ('text', models.TextField(default='default')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RecallModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_recallmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='Testimonials', max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='description',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text_button',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='title',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='alertctamodel',
            name='text',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='alertctamodel',
            name='text_button',
            field=models.CharField(default='default.', max_length=30),
        ),
        migrations.AlterField(
            model_name='alertmdlmodel',
            name='button_title',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='alertmdlmodel',
            name='descriptoin',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='alertmdlmodel',
            name='title',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='alertmdlmodel',
            name='title_bold',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='menubarmodel',
            name='button_text',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='menubarmodel',
            name='locations',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='priceboxmodel',
            name='descriptoin',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='priceboxmodel',
            name='price',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='priceboxmodel',
            name='title',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='pricemodel',
            name='title',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='productsectionmodel',
            name='text',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='productsectionmodel',
            name='title',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='text',
            field=models.CharField(default='default.', max_length=120),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='text_bold',
            field=models.CharField(default='default', max_length=120),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='text_button',
            field=models.CharField(default='default.', max_length=30),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='name_slider',
            field=models.CharField(default='default.', max_length=30),
        ),
        migrations.AlterField(
            model_name='smallfeaturesmodel',
            name='description',
            field=models.TextField(default='default.'),
        ),
        migrations.AlterField(
            model_name='smallfeaturesmodel',
            name='title',
            field=models.CharField(default='default.', max_length=30),
        ),
    ]
