# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0015_aboutusmodel_bg_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='bg_color',
        ),
    ]
