# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0016_remove_aboutusmodel_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='bg_color',
            field=models.CharField(choices=[('Gray', 'bg_gray'), ('Darker', 'bg-primary_darker'), ('White', 'bg-white')], default=('Gray', 'bg_gray'), max_length=30),
        ),
    ]
