# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0017_aboutusmodel_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='bg_color',
            field=models.CharField(choices=[('bg_gray', 'Gray'), ('bg-primary_darker', 'Darker'), ('bg-white', 'White')], default=('bg_gray', 'Gray'), max_length=30),
        ),
    ]
