# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0018_auto_20190416_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='bg_color',
            field=models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30),
        ),
    ]
