# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0019_auto_20190416_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertctamodel',
            name='bg_color',
            field=models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30),
        ),
        migrations.AddField(
            model_name='alertmdlmodel',
            name='bg_color',
            field=models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30),
        ),
        migrations.AddField(
            model_name='lastblogmodel',
            name='bg_color',
            field=models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30),
        ),
        migrations.AddField(
            model_name='pricemodel',
            name='bg_color',
            field=models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30),
        ),
        migrations.AddField(
            model_name='productsectionmodel',
            name='bg_color',
            field=models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30),
        ),
        migrations.AddField(
            model_name='recallmodel',
            name='bg_color',
            field=models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30),
        ),
        migrations.AddField(
            model_name='smallfeaturesmodel',
            name='bg_color',
            field=models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30),
        ),
    ]
