# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('inex_page_home', '0021_contactusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_footermodel', serialize=False, to='cms.CMSPlugin')),
                ('header_1', models.CharField(default='Testimonials', max_length=30)),
                ('header_2', models.CharField(default='Testimonials', max_length=30)),
                ('header_3', models.CharField(default='Testimonials', max_length=30)),
                ('description_1', models.TextField(default='default')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
