# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0022_footermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='footermodel',
            name='description_2',
            field=models.TextField(default='default'),
        ),
    ]
