# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 09:25
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0024_auto_20190417_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(default='default'),
        ),
    ]
