# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 10:48
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inex_page_home', '0025_auto_20190418_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertctamodel',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(default='default'),
        ),
    ]
