# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('inex_page_home', '0026_auto_20190418_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionSectionModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='inex_page_home_solutionsectionmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='default', max_length=30)),
                ('bg_color', models.CharField(choices=[('bg-gray', 'Gray'), ('bg-primary-darker', 'Darker'), ('bg-white', 'White')], default=('bg-gray', 'Gray'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
