# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_descproductmodel_thproductmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('products', models.ManyToManyField(to='product.Product')),
            ],
        ),
    ]
