# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadcrumbsSolution',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='solutions_breadcrumbssolution', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='default', max_length=100)),
                ('title_bold', models.CharField(default='default', max_length=100)),
                ('img', models.ImageField(default='images/def/def.jpg', upload_to='images/breadcrumbsSolution')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=255, verbose_name='Название')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Полное описание')),
                ('implement_period', models.CharField(max_length=255, verbose_name='Срок реализации')),
                ('img', models.ImageField(default='images/def/def.jpg', upload_to='images/solutions', verbose_name='Изображение')),
                ('products', models.ManyToManyField(to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='solutions_solutionspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='default', max_length=30)),
                ('descriptoin', models.TextField(default='default')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
