# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutions',
            name='name',
        ),
        migrations.AddField(
            model_name='solutions',
            name='description',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='solutions',
            name='implement_period',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='solutions',
            name='industry',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
