# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_solutions_background_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='images/def/def.jpg', upload_to='images/recall')),
                ('name', models.CharField(default='default', max_length=30)),
                ('post', models.CharField(default='default', max_length=30)),
                ('text', models.TextField(default='default')),
                ('solutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.Solutions')),
            ],
        ),
    ]
