# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('solutions', '0003_solutions_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='solutions_solutionspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='default', max_length=30)),
                ('descriptoin', models.TextField(default='default')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
