# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('solutions', '0004_solutionspluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadcrumbsSolution',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='solutions_breadcrumbssolution', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='default', max_length=100)),
                ('title_bold', models.CharField(default='default', max_length=100)),
                ('img', models.ImageField(default='images/def/def.jpg', upload_to='images/breadcrumbsSolution')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
