# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0008_auto_20190419_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='img_us',
            field=models.ImageField(default='images/def/def.jpg', upload_to='images/solutions'),
        ),
    ]
