# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0009_solutions_img_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='industry',
            field=models.CharField(default='default', max_length=100, verbose_name='Название'),
        ),
    ]
