# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0010_auto_20190422_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='industry',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
    ]
