# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0011_auto_20190422_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutions',
            name='description_us',
        ),
        migrations.RemoveField(
            model_name='solutions',
            name='img_us',
        ),
        migrations.RemoveField(
            model_name='solutions',
            name='text_button_us',
        ),
        migrations.RemoveField(
            model_name='solutions',
            name='title_us',
        ),
        migrations.AlterField(
            model_name='solutions',
            name='img',
            field=models.ImageField(default='images/def/def.jpg', upload_to='images/solutions', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='implement_period',
            field=models.CharField(max_length=255, verbose_name='Срок реализации'),
        ),
    ]
